version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node:
          steps:
            - run: npm install --prefix ./client
            - run: yarn --cwd ./client test
workflows:
    build-and-test:
      jobs:
        - build-and-test