version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-v1-{{ checksum "yarn.lock" }}
      - run: cd ./client && yarn install
      - run: yarn --cwd ./client test
workflows:
    build-and-test:
      jobs:
        - build-and-test