version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: install client dependencies
          command: yarn --cwd ./client install 
      - run: 
          name: run client tests
          command: yarn --cwd ./client test 
workflows:
    build-and-test:
      jobs:
        - build-and-test