### Download REST Client on VScode to use

GET http://localhost:4000/products/

###

GET http://localhost:4000/products/15

###

POST http://localhost:4000/products/
Content-Type: application/json

{
  "name": "Testing",
  "price": 123,
  "img": "Testing_img_url"
}

###

GET http://localhost:4000/products/:id

###

DELETE http://localhost:4000/products/:id

###

PATCH  http://localhost:4000/products/:id
Content-Type: application/json

{
  "name": "This is another Change part 2"
}
